### PR TITLE
Case-insensitive search for type name

### LINKED ISSUE #662: Regression: 2.10.1:  Error when starting the service
**Summary**. I just tried version 2.10.1 which fixes #659 (service installs fine), but fails to start the service subsequently with the following error in windows event log

## Steps to reproduce
See #659 

The error logged in the event log:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='jenkins'/><EventID Qualifiers='0'>0</EventID><Level>2</Level><Task>0</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2020-08-25T11:11:45.779939800Z'/><EventRecordID>2057</EventRecordID><Channel>Application</Channel><Computer>bh-w2016-18</Computer><Security/></System><EventData><Data>Service cannot be started. WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension ---&gt; WinSW.Extensions.ExtensionException: killOnStartup: Class winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensionFromXml(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)</Data></EventData><RenderingInfo Culture='en-US'><Message>Service cannot be started. WinSW.Extensions.ExtensionException: killOnStartup: Cannot load the class by name: winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension ---&gt; WinSW.Extensions.ExtensionException: killOnStartup: Class winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension does not exist
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   --- End of inner exception stack trace ---
   at WinSW.Extensions.WinSWExtensionManager.CreateExtensionInstance(String id, String className)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensionFromXml(String id)
   at WinSW.Extensions.WinSWExtensionManager.LoadExtensions()
   at WinSW.WrapperService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)</Message><Level>Error</Level><Task></Task><Opcode>Info</Opcode><Channel></Channel><Provider></Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event></Events>
```

## Environment

* WinSW version: 2.10.1
* WinSW package type: nuget
* Windows version: any
* Wrapped executable and version: java

### PR DESCRIPTION
**Pull request by NextTurn**
Fixes #662

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Should have reported it during testing

**Comment by NextTurn** [comment]
I was just about to go another way for the fix.

**Comment by oleg-nenashev** [comment]
@NextTurn Do you still want to do an alternative solution? Or should I go ahead with the release?

**Comment by NextTurn** [comment]
@oleg-nenashev It's #664.

**Comment by oleg-nenashev** [comment]
Ack, did not check the PR description

**Pull request merged**
