### PR TITLE
'If-Modified-Since' support

### PR DESCRIPTION
**Pull request by kvach2avl**
Add support of 'If-Modified-Since' header in request and HTTP/304 in response for resources downloading of the self-updating services

### CODE REVIEW

**Comment by ricardopolo** [comment]
Hello!
Do you have an ETA for releasing this feature?
How can  I help to achieve this?
Thanks

**Comment by oleg-nenashev** [comment]
I hope to get to it tomorrow. Finally should spend time on WinSW

**Comment by ricardopolo** [comment]
Thanks!!! 
Im plannig to release a production software that uses winsw, but dont want to download 100mb every time the service is restarted!!

If you need any help just tell me 😄

**Comment by ricardopolo** [comment]
Hello, I dont want to be pushy, but did you have time to check this out?

Thanks!!

**Comment by oleg-nenashev** [comment]
I tested it locally, and generally it looks good. OTOH i discovered that one of my services always returns 1970-01-01 as a modification time, and the self update stops working there. I will add an opt-out flag before merging

@ricardopolo you can always download the build from the PR builder if you wabt to test it before the release

**Comment by ricardopolo** [comment]
@oleg-nenashev i see you release a new version whitout this PR 😢
Are you still planning to release this feature? I found it very important to dont download the full exe every time we restart the service

**Comment by oleg-nenashev** [comment]
@ricardopolo Yes, I do plan to do so if I have the Windows dev environment. '2.2.0' was a release which was mostly restoring the release flow after a long break

**Comment by oleg-nenashev** [comment]
Good new is that my next laptop will be a Windows one. I should get more opportunities to do the Windows stuff after that

**Comment by ricardopolo** [comment]
Hello @oleg-nenashev, I still believe this feature is very important 😄

**Comment by jeacott1** [comment]
a year on and this still isnt merged. @oleg-nenashev ?

**Comment by oleg-nenashev** [comment]
https://groups.google.com/d/msg/jenkinsci-dev/uc6NsMoCFQI/AIO4WG1UCwAJ pretty much applies to this project as well :( I should have posted announcement somehow here, but have not done it unfortunately. Last November I tried contacting several contributors about becoming co-maintainers, but nobody was interested unfortunately. Although I still want to help with this project, I do not use it on my own ATM. My spare time capacity is also miserable, and critical bits of Jenkins maintenance + GSoC consume all this time unfortunately. I tried to have a GSoC project for WinSW this year, but it did not play out. So I focused on another project critical to the Jenkins community. My apologies to everybody who is waiting for this fix and for other changes.

I have integrated all pull requests which are IMO ready to go, and I will do my best to release them today. Regarding this pull request, I still think in needs opt-out behavior.

If anyone is interested to step up and to co-maintain this repo, I will be happy to do some knowledge transfers after September 10th.

**Comment by oleg-nenashev** [comment]
Superseded by #403 . My apologies for blocking this PR for so long time and not acting on it. I hope with the maintainer team expansion we will be able to fix that

**Pull request closed without merging**
