### PR TITLE
Update CODEOWNERS to request reviews from all maintainers

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I an use a team or setup individual review requests. What would you prefer @NextTurn ?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I will do explicit maintainer mentions then, it is more convenient for external contributors

**Comment by NextTurn** [comment]
Who should the contributors mention (`@`) then if they want to ping on something?

**Comment by oleg-nenashev** [comment]
> Who should the contributors mention (@) then if they want to ping on something?

Individuals. IIRC GitHub still does not allow mentioning public teams if a contributor is not a member of the GitHub organization.

**Comment by oleg-nenashev** [comment]
Fix confirmed in https://github.com/winsw/winsw/pull/448

**Pull request merged**
