### PR TITLE
Fix service crashes

### PR DESCRIPTION
**Pull request by NextTurn**
Back-ports #643

@oleg-nenashev I hope bug fixes can be merged as soon as possible.

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1 for porting

**Comment by oleg-nenashev** [comment]
@NextTurn do you plan to cut the release? Or would you like me to do it?

**Comment by NextTurn** [comment]
I've no special plan.

**Comment by oleg-nenashev** [comment]
Ack. Will release on the weekend or next week once I review/integrate other
patches

**Pull request merged**
