### PR TITLE
Fix versioning of WinSW builds

### LINKED ISSUE #488: Wrong version reported by winsw executable
**The version announced by the winsw executable is incorrect**. Running `winsw.exe version` or `winsw.exe help` prints `WinSW 1.0.0.0` instead of the correct version.

## Steps to reproduce

Download winsw release >= 4.6.0, use provided minimal XML config file, run `winsw.exe version`.

* Actual output: `WinSW 1.0.0.0`
* Expected output: `WinSW 4.6.0.0` (or appropriate)

## Environment

* WinSW version: 2.6.0 to 2.7.0
* WinSW package type: .NET 4.6.1 
* Windows version: Windows Server 2008 R2 Enterprise
* Wrapped executable and version: Java

### PR DESCRIPTION
**Pull request by NextTurn**
Fixes #488

Contributes to #493

### CODE REVIEW

**Comment by NextTurn** [comment]
Tests keep failing. Merge is blocked.

**Comment by oleg-nenashev** [comment]
I relaxed the merge rules for now

**Comment by NextTurn** [comment]
The point is that I don't want to see a bunch of failures in pipelines runs. Will fix the test first.

**Comment by oleg-nenashev** [comment]
> Will fix the test first.

Or just disable it for now

**Pull request merged**
