### PR TITLE
Avoid setting current process environment variables

### PR DESCRIPTION
**Pull request by NextTurn**
That test didn't cover the code paths, but it gave you a lot of confidence?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
.NET2 handling looks like a dark magic to me :(
I will need to get to the test instance before merging it

**Comment by NextTurn** [comment]
> .NET2 handling looks like a dark magic to me :(

There is only one .NET 2 implementation so we can assume the layouts and logic as-is.

**Comment by NextTurn** [comment]
Updated to only use the special codes when **running** on .NET 2.0 -3.5.

**Comment by NextTurn** [comment]
Ping @oleg-nenashev

**Pull request merged**
